Updated README.md
liborioc1/Instagram_SOEN341 pull request #2
Opened 2021-01-24 02:41 UTC by Salma-Elmahallawy

Description, Team Members, and techniques added to README.md

2021-01-24 02:46 UTC, liborioc1 approved these changes

2021-01-24 02:49 UTC, liborioc1 approved these changes

2021-01-24 02:50 UTC, NabilahRouf requested changes
To Do: Add Tarek's GitHub username

2021-01-24 02:50 UTC, melsagh commented
Tarek needs to add his username

2021-01-24 02:52 UTC, liborioc1 requested changes
I think Objective and Description can be a bit more descriptive.

2021-01-24 02:52 UTC, liborioc1 commented on README.md
> +- Tarek El Dick 40110697
Tarek' ID is missing

2021-01-24 02:56 UTC, melsagh commented on README.md
> +- Database : Firebase (NoSQL)
we might go with Mongo though, right?

2021-01-24 02:58 UTC, Salma-Elmahallawy commented on README.md
> +- Database : Firebase (NoSQL)
Yes, we can edit if we end up choosing it.

2021-01-24 03:14 UTC, liborioc1 requested changes
Tarik's username still missing

2021-01-24 19:31 UTC, liborioc1 commented on README.md
> +# SOEN 341: Software Process
Worked on Issue #1  however, missing Username for Tarek

2021-01-24 19:32 UTC, liborioc1 commented on README.md
Worked on #1  Added more to objective and description however, github username is still missing for Tarek

2021-01-24 22:20 UTC, TarekElDick commented on README.md
tarek needs to add his username

2021-01-24 22:21 UTC, TarekElDick commented
tarek needs to add his username

2021-01-24 22:22 UTC, TarekElDick commented
Will add my username

2021-01-24 22:24 UTC, TarekElDick approved these changes
will do !

2021-01-24 22:29 UTC, TarekElDick approved these changes

2021-01-24 22:32 UTC, melsagh approved these changes

2021-01-25 13:55 UTC, liborioc1 approved these changes

2021-01-25 17:46 UTC, NabilahRouf approved these changes

2021-01-25 22:08 UTC, merged